name: ${PROJECT_NAME}

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - lightning=2.0.6
  - torchmetrics=0.11.4
  - hydra-core=1.3.2
  - rich=13.4.2
  - pre-commit=3.2.1
  - pytest=7.4.0
  - wandb=0.15.7
  - pip>=23
  - pip:
      - hydra-colorlog==1.2.0
      - rootutils==1.0.7
      - opencv-python==4.8.0.76
