_target_: lightgan.models.GanModel
channels: 1
width: 28
height: 28

# optimizer:
#   _target_: torch.optim.Adam
#   _partial_: true
#   lr: 0.001
#   weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

# model:
#   _target_: lightgan.models.cycle_gan_model.CycleGanModel

# compile model for faster training with pytorch 2.0
# compile: false
