# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html
early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: ???
  min_delta: 0.
  patience: 3
  verbose: false
  mode: "min"
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: false  # this keyword argument isn't available in stable version
