# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: null
  filename: null
  monitor: null
  verbose: false
  save_last: null
  save_top_k: 1
  mode: "min"
  auto_insert_metric_name: true
  save_weights_only: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
